/***
* BI-CQ2021
* Group 2
* Metadata Database
***/
USE MASTER
GO

-- Action: drop table when creating new database
IF DB_ID('US_AQI_METADATA') IS NOT NULL DROP DATABASE US_AQI_METADATA;

CREATE DATABASE US_AQI_METADATA;
GO

USE US_AQI_METADATA;
GO

-- Action: drop table when creating new schema
DROP TABLE IF EXISTS dbo.DATA_FLOW;

CREATE TABLE DATA_FLOW (
	id INT IDENTITY(1,1),
	name VARCHAR(40),
	LSET DATETIME,
	CET DATETIME,
	CONSTRAINT pk_data_flow primary key (id)
);
GO

DECLARE @LSET DATETIME, @CET DATETIME
SET @LSET = '2024-1-1 00:00:00'
SET @CET = '2024-1-2 00:00:00'

INSERT INTO DATA_FLOW(name, LSET, CET) VALUES ('COUNTY', @LSET, @CET)
INSERT INTO DATA_FLOW(name, LSET, CET) VALUES ('COUNTY_AQI', @LSET, @CET)
INSERT INTO DATA_FLOW(name, LSET, CET) VALUES ('AQI_CATEGORY', @LSET, @CET)